language: python
python:
  - "2.7"
  - "3.6"

# Handle git submodules yourself
git:
    submodules: false

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdal-bin libgdal-dev libgdal1h libgdal1-dev libgeos-dev python-dev python3-dev
  - pip install GDAL==1.10.0 --global-option=build_ext --global-option="-I/usr/include/gdal"
  - pip install -r requirements.txt

before_script:
  - python demo.py -a -d

script: 
# - find . -type f -name "*.py" -not -path "./src/*" -not -path "./build/*"| xargs flake8
  - python -m unittest tests
