language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

# Handle git submodules yourself
git:
    submodules: false

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdal-bin libgdal1i libgdal1-dev libgdal-dev libgeos-dev python-dev python3-dev
  - pip install GDAL==1.11.1 --global-option=build_ext --global-option="-I/usr/include/gdal"
  - pip install -r requirements.txt

before_script:
    "python demo.py -d"

script: "python -m unittest tests"
