say_hello:
  name: "default-config"

ls:
#  dir: './static/data/maps'
  dir: 'd:\Maps'
  pattern: '*.tif'

ras_val:
#  r: './static/data/maps/SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  r: 'd:\Maps\w84geo\dtm_SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
#  r: './static/data/maps/srtm1_x35_y32.tif'
#  r: '@xlink:href=file:./static/data/maps/srtm1_x35_y32.tif'

crop_color:
#  r: './static/data/maps/SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  r: 'd:\Maps\w84geo\dtm_SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
#  r: './static/data/maps/srtm1_x35_y32.tif'
#  color_palette: './static/data/color_files/color_file_1.txt'
  of: 'czml'

viewshed:
#  r: './static/data/maps/SRTM1_hgt.x[27.97,37.98]_y[27.43,37.59].cog.tif'
#  r: 'd:\Maps\srtm3.tif\utm.cog2\*.tif'
  r: 'd:\Maps\w84u36\dtm_SRTM1_hgt_ndv0.w84u36.[31.0, -31.0].x[26.84,40.05]_y[21.8,40.48].scale_0.1.cog.tif'
#  r: './static/data/maps/srtm1_w84u36.tif'
#  r: 'd:\Maps\w84geo\dtm_SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  of: 'czml'
  in_crs: '0'
  out_crs: '0'
  backend: 'talos'

  frequency: 3333.0
  KFactor: 0
  polarity: 'h'
  calc_type: 'PathLoss'

  refractivity: 333.0
  conductivity: 3.0
  permittivity: 33.0
  humidity: 33.0

  power_diff: 100
  fill_center: True
  profile_extension: True

tester:
  r: 'd:\Maps\w84geo\dtm_SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  name: 'Tester'
