say_hello:
  name: "default-config"

ls:
  dir: './static/data/maps'
  pattern: "*.tif"

ras_val:
#  r: './static/data/maps/SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  r: './static/data/maps/srtm1_x35_y32.tif'
#  r: '@xlink:href=file:./static/data/maps/srtm1_x35_y32.tif'

crop_color:
#  r: './static/data/maps/SRTM1_hgt.tif.x20-80_y20-40.cog.tif'
  r: './static/data/maps/srtm1_x35_y32.tif'
#  color_palette: './static/data/color_files/color_file_1.txt'
  of: 'czml'

viewshed:
#  r: './static/data/maps/SRTM1_hgt.x[27.97,37.98]_y[27.43,37.59].cog.tif'
  r: './static/data/maps/srtm1_w84u36.tif'
  of: 'czml'
  in_crs: '0'
  out_crs: '0'
  backend: 'talos'

tester:
  name: 'Idan'
